### PR TITLE
fix: prevent grid items to exceed its container

### LINKED ISSUE #48: [🐛 ] Desktop datatable exceeds the container's width.
The table behaves weirdly and exceeds the container's width on the md (768px) to xl (1280px) screen size. 
Tested on Chrome and Safari.
Below is the demo video.

https://github.com/user-attachments/assets/2ae9ff6e-7473-4f41-a941-356a74b9e210

### PR DESCRIPTION
**Pull request by rhenaldkarrel**
Closes #48.

https://github.com/user-attachments/assets/3204b2ff-b70e-4792-8597-7025e4d01787

### CODE REVIEW

File: src/components/TableUser/data-table.tsx [hunk 1]
```diff
@@ -70,7 +70,7 @@ export function DataTable<TData, TValue>({
   });
 
   return (
-    <div className="grid gap-2">
+    <div className="grid gap-2 grid-cols-1">
```
Comment (mazipan) [inline src/components/TableUser/data-table.tsx:73]: Do we need to explicitly adding class `w-full overflow-x-auto`?

Comment (rhenaldkarrel) [reply src/components/TableUser/data-table.tsx:73]: `overflow-x-auto` is unnecessary since we already wrap the table component with `overflow-auto` for scrollable behaviour.

`w-full` is not needed either because naturally this div will fit its container. 

Cmiiw, mas. 🙏

**Review by mazipan — APPROVED** [review]
LGTM
